### PR TITLE
Add constraint definitions

### PR DESCRIPTION
**Pull request by patrickkwang**

### CODE REVIEW

**Comment by dkoslicki** [comment]
Quick question @patrickkwang , is this intended for the output guarantees only, or also the input requirements? If also the input requirements, we will need to add a bunch more (like the input requirements of PR #7 )

**Comment by cbizon** [comment]
What was the rationale behind removing the constraints on e.g. bind?

**Comment by patrickkwang** [comment]
For bind, I don't see any utility in insisting that the qgraph/kgraph/results exist. If either qgraph or kgraph is missing/empty, or if they are simply incompatible, there should naturally be no results.

**Comment by patrickkwang** [comment]
For fill, similarly, there may simply be no data appropriate for a given qgraph, in which case fill will not add any knowledge.

**Comment by cbizon** [comment]
Fair enough.

**Review by cbizon — APPROVED** [review]

**Review by dkoslicki — APPROVED** [review]

**Pull request merged**
