### PR TITLE
fixed allowlist bug

### PR DESCRIPTION
**Pull request by cbizon**
@sierra-moxon noticed that an operation like
```{ "id": "lookup", "allowlist": ["infores:aragorn"]} ```
was failing validation.

Surprisingly
```{"id": "lookup", "allowlist": {"allowlist": ["infores:aragorn"]}}```
did validate.

This appears to have been caused by a recent refactoring creating the AllowList and DenyList jsonschema definitions.

The problem is that these are meant to be a "oneOf", but there is no way to decide between them because they don't have `additionalProperties: False` in their definitions or required elements.  So just having "allowlist" in there could mean you are a DenyList without a denylist property but with an allowlist property.   Adding additionalProperties:False worked, though I can't claim a thorough understanding of all the ins and outs of json schema here.

### CODE REVIEW

**Comment by dkoslicki** [comment]
Oof, waiting for @RichardBruskiewich or @uhbrar who know more than I do about the validation than I do.

**Review by uhbrar — CHANGES_REQUESTED** [review]
As far as I know, `{ "id": "lookup", "allowlist": ["infores:aragorn"]}` shouldn't validate.

There are two appropriate uses of key values "allowlist" and "denylist". The first is as a operation base parameter of OperationFill, which is specified in the "parameters" field of the operation like so: 

```
{
     "id": "fill",
     "parameters": {
          "allowlist": ["infores:aragorn"]
      }
}
```
This only applies to OperationFill and no other operation, so of course, this doesn't have anything to do with lookup.

The other case in which "allowlist" or "denylist" are expected key values is when they are defined as a part of the "runner_parameters" for an operation. This applies to all operations and would look like this:

```
{
     "id": "lookup",
     "runner_parameters": {
          "allowlist": ["infores:aragorn"]
     }
}
```

It seems as though this most closely matches what you were describing in the original post. I suspect that `"allowlist": {"allowlist":["infores:aragorn"]}` validates for some reason because "allowlist" is an expected second level key value for an operation property (either "parameters" or "runner_parameters"). 

We need to track down where in the schema this has gone wrong. I'm no expert on JSON schema, but my intuition is that this can be fixed by changing AllowList and DenyList from objects to arrays, getting rid of their self-named properties, and then adding two properties named "allowlist" and "denylist" to RunnerParameters that would utilize the oneOf paradigm and define each property to be of the corresponding type.

**Comment by cbizon** [comment]
Thanks @uhbrar that's very helpful.

**Comment by cbizon** [comment]
Upon further review, the code works as you suggested @uhbrar , it was my comment on the PR that was wrong.   I've added a test to show the behavior.

**Comment by uhbrar** [comment]
Do we want to have the tests pass before we merge this in? Looks like there's some kind of dependency issue.

**Comment by cbizon** [comment]
Commit in haste, repent in leisure.  Tests fixed now.

**Review by uhbrar — APPROVED** [review]
Looks good now!

**Pull request merged**
