### PR TITLE
Specify that contraints must be respected in the fill/lookup/lookup_and_score descriptions

### PR DESCRIPTION
**Pull request by finnagin**

### CODE REVIEW

**Review by edeutsch — APPROVED** [review]
Yeah, pretty good, I might suggest being slightly more specific, saying that "Any constraints attached to QNodes and QEdges must be handled". But essentially fine.

**Comment by finnagin** [comment]
@edeutsch I've updated the description to specify the QNodes and QEdges. Okay to merge?

**Review by edeutsch — APPROVED** [review]
looks good, thanks!

**Comment by uhbrar** [comment]
I didn't see this before, but there is actually one thing of note here. I think we should be wary of over-incrementing the versioning of our the schema jsons. Using the generate script will automatically increment the version, so in this pr, the version jumps from 1.2 to 1.4. I think this is something we should avoid doing.

**Comment by finnagin** [comment]
Ah I see. If changes like this should be batched under the minor number would it make sense to alter the auto version incrementing code to bump the 3rd level instead of the 2nd level and then we manually increment the minor level when we feel enough has changed? I.E. instead of 1.2.0 -> 1.3.0 it would have been 1.2.0 -> 1.2.1

**Pull request merged**
